# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TermProjcet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TermProjcet

  pod 'FSCalendar'
  pod 'DropDown'
  pod 'Gifu'
  pod 'MaterialComponents/BottomSheet' 
  pod 'Charts'
  pod 'YouTubePlayer'
  pod 'Tabman', '~> 2.9'
  pod 'Toast-Swift', '~> 5.0.1'

end
